name: Update Native Agent Version
on:
  workflow_dispatch:
    inputs:
      VERSION_NUMBER:
        required: true
        type: string
      IS_ANDROID_AGENT:
        required: true
        type: boolean
jobs:
  update_agent_version:
    name: Update Native Agent version on Capacitor
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Update version number
        run: |
          if ${{ github.event.inputs.IS_ANDROID_AGENT }}
          then
            sed -i 's/com.newrelic.agent.android:agent-gradle-plugin:.*/com.newrelic.agent.android:agent-gradle-plugin:${{ github.event.inputs.VERSION_NUMBER }}\"/' README.md
            sed -i 's/com.newrelic.agent.android:agent-gradle-plugin:.*/com.newrelic.agent.android:agent-gradle-plugin:${{ github.event.inputs.VERSION_NUMBER }}'\''/' android/build.gradle
            sed -i 's/com.newrelic.agent.android:android-agent:.*/com.newrelic.agent.android:android-agent:${{ github.event.inputs.VERSION_NUMBER }}'\''/' android/build.gradle
          else 
            sed -i 's/'\''NewRelicAgent'\'', .*/'\''NewRelicAgent'\'', '\''${{ github.event.inputs.VERSION_NUMBER }}'\''/' NewrelicNewrelicCapacitorPlugin.podspec
            sed -i 's/pod '\''NewRelicAgent'\'', .*/pod '\''NewRelicAgent'\'', '\''${{ github.event.inputs.VERSION_NUMBER }}'\''/' ios/Podfile
          fi
      - name: Setup GitHub Credentials
        run: |
          git config user.name $GITHUB_ACTOR
          git config user.email gh-actions-${GITHUB_ACTOR}@github.com
      - name: Push Changes to GitHub
        run: |
          if ${{ github.event.inputs.IS_ANDROID_AGENT }}
          then
            AGENT_NAME="Android"
          else
            AGENT_NAME="iOS"
          fi
          git checkout -b "update_${AGENT_NAME}_ver_${{ github.event.inputs.VERSION_NUMBER }}"
          git add README.md android/build.gradle NewrelicNewrelicCapacitorPlugin.podspec ios/Podfile
          git commit -m "Update $AGENT_NAME Version to ${{ github.event.inputs.VERSION_NUMBER }}"
          git remote -v
          git push origin HEAD
          gh pr create -B "develop" -H "update_${AGENT_NAME}_ver_${{ github.event.inputs.VERSION_NUMBER }}" --title "Update ${AGENT_NAME} agent to ${{ github.event.inputs.VERSION_NUMBER }}" --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
